services:
    mysql_container:
        image: mysql:latest
        container_name: "dev_java_sql_container"
        environment:
            MYSQL_ROOT_PASSWORD: java
        ports:
            - "3306:3306"
        # volumes:
        #     - "./sql/setup.sql:/docker-entrypoint-initdb.d/1.sql"
