version: "3.9"
services:
    mongodb_container:
        image: mongo:latest
        container_name: "dev_java_mongo_container"
        environment:
            MONGO_INITDB_ROOT_USERNAME: java
            MONGO_INITDB_ROOT_PASSWORD: java2024
            MONGO_INITDB_DATABASE: playground-web
        ports:
            - 27017:27017
        volumes:
            - mongodb_java_container:/data/db

volumes:
    mongodb_java_container:
