include ../Makefile.mk

## Up offcial opensearch docker cluster using docker. | Docker
opensearch:
	docker-compose -f ./offcial-opensearch.yaml up -d

## Up simple opensearch docker cluster using docker.
simple:
	docker-compose -f ./simple-opensearch.yaml up -d
